# Generated by Django 5.0.6 on 2025-01-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("task", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
